### ISSUE TITLE
H_(A|V)RULE naming convetions in glue.h

### ISSUE THREAD

**Issue by c-alpha** [abiggerhammer/hammer#40]
Currently, the naming conventions for the action and validation functions are:
```
act_<rulename>
validate_<rulename>
```
One is an abbreviated form, one a full form, and the user must remember which case uses which. It's probably more boring, but IMO easier to remember (and hence less likely to get wrong) if both would use either the full, or both the abbreviated form. I.e. either
```
action_<rulename>
validate_<rulename>
```
or
```
act_<rulename>
val_<rulename>
```
Looking forward to your thoughts.

**Comment by pesco** [comment]
Just a point of note here: "act" is not an abbreviation, but a verb (an imperative) - like "validate".
